spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blunk
    username: postgres
    password: 1500002006501
    driver-class-name: org.postgresql.Driver


  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

  sql:
    init:
      mode: never
      continue-on-error: false
      data-locations: classpath:demo_data.sql