@startuml
'https://plantuml.com/activity-diagram-beta

start
:Выбор товара пользователем;
:Нажатие на изображение выбранного товара;
:Открытие страницы выбранного товара;
:Выбор размера товара;
:Выбор цвета товара;
stop
@enduml
