@startuml
'https://plantuml.com/deployment-diagram


skinparam{
FileAlign top right
MessageAlign center
}

node "Computer (Windows 10)"{
artifact Browser
node "Computer display/monitor"

node Server

artifact PostgreSQL
"Computer display/monitor" - Browser

Browser - Server

Server - PostgreSQL
}


@enduml